# Generated by Django 3.1.7 on 2021-05-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210503_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='desciption',
            field=models.TextField(default='play the Quiz', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='media/sub_images/default_sub.jpg', upload_to='media/sub_images'),
        ),
    ]
