# Generated by Django 3.1.7 on 2021-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20210506_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='media/sub_images/default_sub.jpg', upload_to='sub_images'),
        ),
    ]
