# Generated by Django 3.1.7 on 2021-05-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210506_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='desciption',
            new_name='description',
        ),
    ]
